name: Check

on:
  pull_request:
    branches:
      - main
      - develop
      - feature/*

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run TypeScript typecheck and annotate PR
        uses: reviewdog/action-tsc@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_on_error: true
