name: Merge Group

on:
  merge_group:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Skipped"
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Skipped"
  version:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Skipped"
