name: Check

on:
  pull_request:
    branches:
      - develop
  merge_group: 
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Install reviewdog
        uses: reviewdog/action-setup@v1
      - name: Run tsc and report with reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx tsc --noEmit --pretty false 2>&1 \
            | reviewdog -efm="%f(%l,%c): error %m" \
                -name="tsc" \
                -reporter=github-pr-review \
  test:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ">=20.0.0"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Install reviewdog
        uses: reviewdog/action-setup@v1
      - name: Test with coverage
        env:
          CI: true
          NODE_ENV: test
          VITEST_TIMEOUT: 10000
          VITEST_REPORTER: text
          VITEST_REPORTER_OPTIONS: summary,verbose
        run: npm run test:coverage
      - name: Report coverage with reviewdog
        uses: aki77/reviewdog-action-code-coverage@v2
        with:
          lcov_path: ./**/coverage/lcov.info
          tool_name: vitest
          filter_mode: diff_context
      - name: Check coverage thresholds
        run: |
          npx vitest run --coverage --reporter=text
        continue-on-error: true
      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            **/coverage/
            **/coverage/lcov-report/
          retention-days: 30
