name: Release PR

on:
  workflow_run:
    workflows: ["Version"]
    types:
      - completed
    branches:
      - release/*

permissions:
  contents: write
  pull-requests: write

jobs:
  open-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: ${{ github.ref_name }}
          base: main
          title: ${{ github.ref_name }}
          body: |
            This is a release PR for the ${{ github.ref_name }} release.
            It will be merged into the main branch.
          labels: release
          draft: true
