name: Test

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - feature/*
      - hotfix/*
      - release/*
  merge_group:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ">=20.0.0"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test
        env:
          CI: true
          NODE_ENV: test
          VITEST_TIMEOUT: 10000
          VITEST_REPORTER: dot
          VITEST_REPORTER_OPTIONS: summary,verbose
