name: Version & Open PR

on:
  push:
    branches:
      - develop

permissions:
  contents: write
  packages: write

jobs:
  version:
    outputs:
      branch: ${{ steps.version.outputs.branch }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ">=20.0.0"
          cache: "npm"
      - uses: bahulneel/action-version@v0.28.6
        id: version
        with:
          branch: ?1
          branch_deletion: prune
        
  open-pr:
    needs: version
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Debug Branch Name from Previous Job
        run: "echo Release Branch Name received: ${{ needs.version.outputs.branch }}"
      
      - name: Create Pull Request to Main using GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Authenticate GitHub CLI with the GITHUB_TOKEN
        run: |
          RELEASE_BRANCH="${{ needs.version.outputs.branch }}"
          echo "Attempting to create PR from $RELEASE_BRANCH to main"

          # Use gh pr create command
          gh pr create \
            --title "Release PR for $RELEASE_BRANCH" \
            --body "This is an automated release PR for $RELEASE_BRANCH. Please review and merge into the main branch." \
            --base "main" \
            --head "$RELEASE_BRANCH" \
            --label "release" \
            --draft # Keep it as a draft PR

          echo "Pull Request creation command executed."
