name: Version

on:
  pull_request:
    branches: [develop]

# Add permissions block at the workflow level
permissions:
  contents: write
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # This ensures we get all commits for version analysis
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: bahulneel/action-version@v0.15.0
