name: Version

on:
  push:
    branches:
      - develop

permissions:
  contents: write
  packages: write

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: bahulneel/action-version@main
        with:
          branch: ?1
