name: Version & Open PR

on:
  push:
    branches:
      - develop

permissions:
  contents: write
  packages: write

jobs:
  version:
    outputs:
      branch: ${{ steps.version.outputs.branch }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ">=20.0.0"
          cache: "npm"
      - uses: bahulneel/action-version@v0.28.3
        id: version
        with:
          branch: ?1
          branch_deletion: prune
        
  open-pr:
    runs-on: ubuntu-latest
    needs: version
    steps:
      # Checkout the new release branch to ensure the PR is created from the correct state
      - name: Checkout Release Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.version.outputs.branch }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          # Use the branch name passed from the previous workflow's output
          branch: ${{ needs.version.outputs.branch }}
          base: main
          title: 'Release ${{ needs.version.outputs.branch }}'
          body: |
            This is an automated release PR for ${{ needs.version.outputs.branch }}.
            Please review and merge into the main branch.
          labels: release
          draft: true
          # Ensure this token has 'pull-requests: write' and 'contents: write' permissions
          token: ${{ secrets.GITHUB_TOKEN }}